package tech.zolhungaj.amqapi;

import java.net.URI;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public final class Emojis {
    private Emojis(){}
    private static final Map<String, String> SHORTCODE_MAP = new HashMap<>();
    private static final URI BASE_PATH = URI.create("https://animemusicquiz.com/");

    private static final URI EMOJI_BASE_PATH = BASE_PATH.resolve("/emoji");
    static {
        Map<String, int[]> temp = new HashMap<>();

        temp.put(":ideograph_advantage:", new int[]{0x1f250});
        temp.put(":ophiuchus:", new int[]{0x26ce});
        temp.put(":flag-gt:", new int[]{0x1f1ec, 0x1f1f9});
        temp.put(":label:", new int[]{0x1f3f7});
        temp.put(":gift_heart:", new int[]{0x1f49d});
        temp.put(":headphones:", new int[]{0x1f3a7});
        temp.put(":baggage_claim:", new int[]{0x1f6c4});
        temp.put(":crossed_swords:", new int[]{0x2694});
        temp.put(":flag-sy:", new int[]{0x1f1f8, 0x1f1fe});
        temp.put(":barber:", new int[]{0x1f488});
        temp.put(":astonished:", new int[]{0x1f632});
        temp.put(":bath:", new int[]{0x1f6c0});
        temp.put(":flag-uz:", new int[]{0x1f1fa, 0x1f1ff});
        temp.put(":flag-jm:", new int[]{0x1f1ef, 0x1f1f2});
        temp.put(":poodle:", new int[]{0x1f429});
        temp.put(":sweat:", new int[]{0x1f613});
        temp.put(":massage:", new int[]{0x1f486});
        temp.put(":small_red_triangle:", new int[]{0x1f53a});
        temp.put(":arrow_down_small:", new int[]{0x1f53d});
        temp.put(":full_moon:", new int[]{0x1f315});
        temp.put(":flag-na:", new int[]{0x1f1f3, 0x1f1e6});
        temp.put(":cop:", new int[]{0x1f46e});
        temp.put(":disappointed:", new int[]{0x1f61e});
        temp.put(":cityscape:", new int[]{0x1f3d9});
        temp.put(":person_with_pouting_face:", new int[]{0x1f64e});
        temp.put(":flag-uy:", new int[]{0x1f1fa, 0x1f1fe});
        temp.put(":flag-sj:", new int[]{0x1f1f8, 0x1f1ef});
        temp.put(":video_camera:", new int[]{0x1f4f9});
        temp.put(":question:", new int[]{0x2753});
        temp.put(":radioactive:", new int[]{0x2622});
        temp.put(":bullettrain_front:", new int[]{0x1f685});
        temp.put(":kissing_cat:", new int[]{0x1f63d});
        temp.put(":clock430:", new int[]{0x1f55f});
        temp.put(":u7981:", new int[]{0x1f232});
        temp.put(":two_men_holding_hands:", new int[]{0x1f46c});
        temp.put(":pig_nose:", new int[]{0x1f43d});
        temp.put(":railway_car:", new int[]{0x1f683});
        temp.put(":poop:", new int[]{0x1f4a9});
        temp.put(":tanabata_tree:", new int[]{0x1f38b});
        temp.put(":light_rail:", new int[]{0x1f688});
        temp.put(":cl:", new int[]{0x1f191});
        temp.put(":bridge_at_night:", new int[]{0x1f309});
        temp.put(":yen:", new int[]{0x1f4b4});
        temp.put(":flag-bn:", new int[]{0x1f1e7, 0x1f1f3});
        temp.put(":grimacing:", new int[]{0x1f62c});
        temp.put(":weary:", new int[]{0x1f629});
        temp.put(":tomato:", new int[]{0x1f345});
        temp.put(":flag-gl:", new int[]{0x1f1ec, 0x1f1f1});
        temp.put(":flag-kz:", new int[]{0x1f1f0, 0x1f1ff});
        temp.put(":boom:", new int[]{0x1f4a5});
        temp.put(":microphone:", new int[]{0x1f3a4});
        temp.put(":angry:", new int[]{0x1f620});
        temp.put(":smirk:", new int[]{0x1f60f});
        temp.put(":clock1:", new int[]{0x1f550});
        temp.put(":flag-pm:", new int[]{0x1f1f5, 0x1f1f2});
        temp.put(":black_medium_small_square:", new int[]{0x25fe});
        temp.put(":u5272:", new int[]{0x1f239});
        temp.put(":haircut:", new int[]{0x1f487});
        temp.put(":flag-gi:", new int[]{0x1f1ec, 0x1f1ee});
        temp.put(":sound:", new int[]{0x1f509});
        temp.put(":vs:", new int[]{0x1f19a});
        temp.put(":underage:", new int[]{0x1f51e});
        temp.put(":up:", new int[]{0x1f199});
        temp.put(":flag-ls:", new int[]{0x1f1f1, 0x1f1f8});
        temp.put(":japanese_castle:", new int[]{0x1f3ef});
        temp.put(":flag-nr:", new int[]{0x1f1f3, 0x1f1f7});
        temp.put(":minibus:", new int[]{0x1f690});
        temp.put(":flag-ps:", new int[]{0x1f1f5, 0x1f1f8});
        temp.put(":guitar:", new int[]{0x1f3b8});
        temp.put(":flag-kp:", new int[]{0x1f1f0, 0x1f1f5});
        temp.put(":leftwards_arrow_with_hook:", new int[]{0x21a9});
        temp.put(":flag-mt:", new int[]{0x1f1f2, 0x1f1f9});
        temp.put(":chart_with_downwards_trend:", new int[]{0x1f4c9});
        temp.put(":smiley:", new int[]{0x1f603});
        temp.put(":place_of_worship:", new int[]{0x1f6d0});
        temp.put(":crown:", new int[]{0x1f451});
        temp.put(":bank:", new int[]{0x1f3e6});
        temp.put(":rage:", new int[]{0x1f621});
        temp.put(":arrow_upper_right:", new int[]{0x2197});
        temp.put(":flag-kg:", new int[]{0x1f1f0, 0x1f1ec});
        temp.put(":worried:", new int[]{0x1f61f});
        temp.put(":bee:", new int[]{0x1f41d});
        temp.put(":clapper:", new int[]{0x1f3ac});
        temp.put(":thinking:", new int[]{0x1f914});
        temp.put(":flag-is:", new int[]{0x1f1ee, 0x1f1f8});
        temp.put(":airplane:", new int[]{0x2708});
        temp.put(":sa:", new int[]{0x1f202});
        temp.put(":slot_machine:", new int[]{0x1f3b0});
        temp.put(":joystick:", new int[]{0x1f579});
        temp.put(":flag-id:", new int[]{0x1f1ee, 0x1f1e9});
        temp.put(":cow2:", new int[]{0x1f404});
        temp.put(":smiling_imp:", new int[]{0x1f608});
        temp.put(":clock230:", new int[]{0x1f55d});
        temp.put(":fr:", new int[]{0x1f1eb});
        temp.put(":milky_way:", new int[]{0x1f30c});
        temp.put(":flag-vi:", new int[]{0x1f1fb, 0x1f1ee});
        temp.put(":tophat:", new int[]{0x1f3a9});
        temp.put(":flag_ag:", new int[]{0x1f1e6, 0x1f1ec});
        temp.put(":page_with_curl:", new int[]{0x1f4c3});
        temp.put(":flag-bf:", new int[]{0x1f1e7, 0x1f1eb});
        temp.put(":crab:", new int[]{0x1f980});
        temp.put(":fireworks:", new int[]{0x1f386});
        temp.put(":steam_locomotive:", new int[]{0x1f682});
        temp.put(":womans_clothes:", new int[]{0x1f45a});
        temp.put(":fire_engine:", new int[]{0x1f692});
        temp.put(":flag-me:", new int[]{0x1f1f2, 0x1f1ea});
        temp.put(":purse:", new int[]{0x1f45b});
        temp.put(":hushed:", new int[]{0x1f62f});
        temp.put(":flag-tn:", new int[]{0x1f1f9, 0x1f1f3});
        temp.put(":microscope:", new int[]{0x1f52c});
        temp.put(":control_knobs:", new int[]{0x1f39b});
        temp.put(":sake:", new int[]{0x1f376});
        temp.put(":sunrise:", new int[]{0x1f305});
        temp.put(":rice:", new int[]{0x1f35a});
        temp.put(":flag-eh:", new int[]{0x1f1ea, 0x1f1ed});
        temp.put(":alarm_clock:", new int[]{0x23f0});
        temp.put(":kiss:", new int[]{0x1f48b});
        temp.put(":flag-cz:", new int[]{0x1f1e8, 0x1f1ff});
        temp.put(":honey_pot:", new int[]{0x1f36f});
        temp.put(":small_red_triangle_down:", new int[]{0x1f53b});
        temp.put(":flag-dm:", new int[]{0x1f1e9, 0x1f1f2});
        temp.put(":flag-mw:", new int[]{0x1f1f2, 0x1f1fc});
        temp.put(":flag-ir:", new int[]{0x1f1ee, 0x1f1f7});
        temp.put(":hourglass:", new int[]{0x231b});
        temp.put(":flag-dz:", new int[]{0x1f1e9, 0x1f1ff});
        temp.put(":capricorn:", new int[]{0x2651});
        temp.put(":fried_shrimp:", new int[]{0x1f364});
        temp.put(":flag-sh:", new int[]{0x1f1f8, 0x1f1ed});
        temp.put(":slight_smile:", new int[]{0x1f642});
        temp.put(":flag-tf:", new int[]{0x1f1f9, 0x1f1eb});
        temp.put(":diamond_shape_with_a_dot_inside:", new int[]{0x1f4a0});
        temp.put(":see_no_evil:", new int[]{0x1f648});
        temp.put(":flag-fo:", new int[]{0x1f1eb, 0x1f1f4});
        temp.put(":octagonal_sign:", new int[]{0x1f6d1});
        temp.put(":white_medium_small_square:", new int[]{0x25fd});
        temp.put(":flag-vn:", new int[]{0x1f1fb, 0x1f1f3});
        temp.put(":flag-hu:", new int[]{0x1f1ed, 0x1f1fa});
        temp.put(":baby_symbol:", new int[]{0x1f6bc});
        temp.put(":point_down:", new int[]{0x1f447});
        temp.put(":palm_tree:", new int[]{0x1f334});
        temp.put(":european_castle:", new int[]{0x1f3f0});
        temp.put(":flag-sb:", new int[]{0x1f1f8, 0x1f1e7});
        temp.put(":mans_shoe:", new int[]{0x1f45e});
        temp.put(":package:", new int[]{0x1f4e6});
        temp.put(":mountain:", new int[]{0x26f0});
        temp.put(":taxi:", new int[]{0x1f695});
        temp.put(":free:", new int[]{0x1f193});
        temp.put(":six:", new int[]{0x0036, 0x20e3});
        temp.put(":white_small_square:", new int[]{0x25ab});
        temp.put(":white_check_mark:", new int[]{0x2705});
        temp.put(":lemon:", new int[]{0x1f34b});
        temp.put(":flag-mk:", new int[]{0x1f1f2, 0x1f1f0});
        temp.put(":heart_decoration:", new int[]{0x1f49f});
        temp.put(":flag-mq:", new int[]{0x1f1f2, 0x1f1f6});
        temp.put(":flag-om:", new int[]{0x1f1f4, 0x1f1f2});
        temp.put(":flag-ic:", new int[]{0x1f1ee, 0x1f1e8});
        temp.put(":corn:", new int[]{0x1f33d});
        temp.put(":persevere:", new int[]{0x1f623});
        temp.put(":japan:", new int[]{0x1f5fe});
        temp.put(":pick:", new int[]{0x26cf});
        temp.put(":man:", new int[]{0x1f468});
        temp.put(":wine_glass:", new int[]{0x1f377});
        temp.put(":flag-lt:", new int[]{0x1f1f1, 0x1f1f9});
        temp.put(":sweat_drops:", new int[]{0x1f4a6});
        temp.put(":flag-cf:", new int[]{0x1f1e8, 0x1f1eb});
        temp.put(":octopus:", new int[]{0x1f419});
        temp.put(":heavy_minus_sign:", new int[]{0x2796});
        temp.put(":flag-bt:", new int[]{0x1f1e7, 0x1f1f9});
        temp.put(":tired_face:", new int[]{0x1f62b});
        temp.put(":video_game:", new int[]{0x1f3ae});
        temp.put(":partly_sunny:", new int[]{0x26c5});
        temp.put(":lock_with_ink_pen:", new int[]{0x1f50f});
        temp.put(":flag-tl:", new int[]{0x1f1f9, 0x1f1f1});
        temp.put(":broken_heart:", new int[]{0x1f494});
        temp.put(":flag-tv:", new int[]{0x1f1f9, 0x1f1fb});
        temp.put(":soon:", new int[]{0x1f51c});
        temp.put(":wrench:", new int[]{0x1f527});
        temp.put(":flag-qa:", new int[]{0x1f1f6, 0x1f1e6});
        temp.put(":izakaya_lantern:", new int[]{0x1f3ee});
        temp.put(":open_hands:", new int[]{0x1f450});
        temp.put(":five:", new int[]{0x0035, 0x20e3});
        temp.put(":white_medium_square:", new int[]{0x25fb});
        temp.put(":panda_face:", new int[]{0x1f43c});
        temp.put(":large_orange_diamond:", new int[]{0x1f536});
        temp.put(":bikini:", new int[]{0x1f459});
        temp.put(":flag-jo:", new int[]{0x1f1ef, 0x1f1f4});
        temp.put(":spaghetti:", new int[]{0x1f35d});
        temp.put(":ice_cream:", new int[]{0x1f368});
        temp.put(":cat2:", new int[]{0x1f408});
        temp.put(":confused:", new int[]{0x1f615});
        temp.put(":fish:", new int[]{0x1f41f});
        temp.put(":dog2:", new int[]{0x1f415});
        temp.put(":monkey:", new int[]{0x1f412});
        temp.put(":joy:", new int[]{0x1f602});
        temp.put(":trophy:", new int[]{0x1f3c6});
        temp.put(":flag-tj:", new int[]{0x1f1f9, 0x1f1ef});
        temp.put(":hearts:", new int[]{0x2665});
        temp.put(":flag-fi:", new int[]{0x1f1eb, 0x1f1ee});
        temp.put(":mailbox_closed:", new int[]{0x1f4ea});
        temp.put(":clubs:", new int[]{0x2663});
        temp.put(":u7533:", new int[]{0x1f238});
        temp.put(":flag_black:", new int[]{0x1f3f4});
        temp.put(":flag-ug:", new int[]{0x1f1fa, 0x1f1ec});
        temp.put(":arrow_backward:", new int[]{0x25c0});
        temp.put(":information_desk_person:", new int[]{0x1f481});
        temp.put(":dizzy:", new int[]{0x1f4ab});
        temp.put(":black_square_button:", new int[]{0x1f532});
        temp.put(":flag-bg:", new int[]{0x1f1e7, 0x1f1ec});
        temp.put(":flag-kh:", new int[]{0x1f1f0, 0x1f1ed});
        temp.put(":flag-md:", new int[]{0x1f1f2, 0x1f1e9});
        temp.put(":no_bell:", new int[]{0x1f515});
        temp.put(":flashlight:", new int[]{0x1f526});
        temp.put(":flag-ss:", new int[]{0x1f1f8, 0x1f1f8});
        temp.put(":film_frames:", new int[]{0x1f39e});
        temp.put(":smiley_cat:", new int[]{0x1f63a});
        temp.put(":cocktail:", new int[]{0x1f378});
        temp.put(":coffin:", new int[]{0x26b0});
        temp.put(":flag-um:", new int[]{0x1f1fa, 0x1f1f2});
        temp.put(":oncoming_bus:", new int[]{0x1f68d});
        temp.put(":white_square_button:", new int[]{0x1f533});
        temp.put(":flag-pa:", new int[]{0x1f1f5, 0x1f1e6});
        temp.put(":flag-ck:", new int[]{0x1f1e8, 0x1f1f0});
        temp.put(":whale:", new int[]{0x1f433});
        temp.put(":arrow_lower_left:", new int[]{0x2199});
        temp.put(":flag-lr:", new int[]{0x1f1f1, 0x1f1f7});
        temp.put(":flag-pf:", new int[]{0x1f1f5, 0x1f1eb});
        temp.put(":point_left:", new int[]{0x1f448});
        temp.put(":flag-it:", new int[]{0x1f1ee, 0x1f1f9});
        temp.put(":oden:", new int[]{0x1f362});
        temp.put(":cow:", new int[]{0x1f42e});
        temp.put(":telephone:", new int[]{0x260e});
        temp.put(":disappointed_relieved:", new int[]{0x1f625});
        temp.put(":hear_no_evil:", new int[]{0x1f649});
        temp.put(":skull:", new int[]{0x1f480});
        temp.put(":secret:", new int[]{0x3299});
        temp.put(":flag-ht:", new int[]{0x1f1ed, 0x1f1f9});
        temp.put(":file_folder:", new int[]{0x1f4c1});
        temp.put(":anguished:", new int[]{0x1f627});
        temp.put(":poultry_leg:", new int[]{0x1f357});
        temp.put(":flag-ga:", new int[]{0x1f1ec, 0x1f1e6});
        temp.put(":walking:", new int[]{0x1f6b6});
        temp.put(":ferry:", new int[]{0x26f4});
        temp.put(":person_frowning:", new int[]{0x1f64d});
        temp.put(":cyclone:", new int[]{0x1f300});
        temp.put(":cinema:", new int[]{0x1f3a6});
        temp.put(":horse:", new int[]{0x1f434});
        temp.put(":paperclip:", new int[]{0x1f4ce});
        temp.put(":triangular_ruler:", new int[]{0x1f4d0});
        temp.put(":clock12:", new int[]{0x1f55b});
        temp.put(":arrow_up_down:", new int[]{0x2195});
        temp.put(":evergreen_tree:", new int[]{0x1f332});
        temp.put(":train2:", new int[]{0x1f686});
        temp.put(":japanese_goblin:", new int[]{0x1f47a});
        temp.put(":ambulance:", new int[]{0x1f691});
        temp.put(":bento:", new int[]{0x1f371});
        temp.put(":three:", new int[]{0x0033, 0x20e3});
        temp.put(":on:", new int[]{0x1f51b});
        temp.put(":confounded:", new int[]{0x1f616});
        temp.put(":biohazard:", new int[]{0x2623});
        temp.put(":airplane_departure:", new int[]{0x1f6eb});
        temp.put(":flag-cr:", new int[]{0x1f1e8, 0x1f1f7});
        temp.put(":flag-se:", new int[]{0x1f1f8, 0x1f1ea});
        temp.put(":clock9:", new int[]{0x1f558});
        temp.put(":arrow_right_hook:", new int[]{0x21aa});
        temp.put(":heavy_dollar_sign:", new int[]{0x1f4b2});
        temp.put(":dress:", new int[]{0x1f457});
        temp.put(":pager:", new int[]{0x1f4df});
        temp.put(":seven:", new int[]{0x0037, 0x20e3});
        temp.put(":low_brightness:", new int[]{0x1f505});
        temp.put(":flag-gm:", new int[]{0x1f1ec, 0x1f1f2});
        temp.put(":speech_left:", new int[]{0x1f5e8});
        temp.put(":bug:", new int[]{0x1f41b});
        temp.put(":bird:", new int[]{0x1f426});
        temp.put(":smile_cat:", new int[]{0x1f638});
        temp.put(":speech_balloon:", new int[]{0x1f4ac});
        temp.put(":stew:", new int[]{0x1f372});
        temp.put(":u55b6:", new int[]{0x1f23a});
        temp.put(":japanese_ogre:", new int[]{0x1f479});
        temp.put(":droplet:", new int[]{0x1f4a7});
        temp.put(":fog:", new int[]{0x1f32b});
        temp.put(":flag-pr:", new int[]{0x1f1f5, 0x1f1f7});
        temp.put(":flag_al:", new int[]{0x1f1e6, 0x1f1f1});
        temp.put(":flag-va:", new int[]{0x1f1fb, 0x1f1e6});
        temp.put(":skull_crossbones:", new int[]{0x2620});
        temp.put(":flag-ao:", new int[]{0x1f1e6, 0x1f1f4});
        temp.put(":school_satchel:", new int[]{0x1f392});
        temp.put(":kissing_heart:", new int[]{0x1f618});
        temp.put(":recycle:", new int[]{0x267b});
        temp.put(":cupid:", new int[]{0x1f498});
        temp.put(":closed_umbrella:", new int[]{0x1f302});
        temp.put(":put_litter_in_its_place:", new int[]{0x1f6ae});
        temp.put(":doughnut:", new int[]{0x1f369});
        temp.put(":blowfish:", new int[]{0x1f421});
        temp.put(":flag-cx:", new int[]{0x1f1e8, 0x1f1fd});
        temp.put(":eyeglasses:", new int[]{0x1f453});
        temp.put(":flag_wf:", new int[]{0x1f1fc, 0x1f1eb});
        temp.put(":u5408:", new int[]{0x1f234});
        temp.put(":bathtub:", new int[]{0x1f6c1});
        temp.put(":wheel_of_dharma:", new int[]{0x2638});
        temp.put(":dog:", new int[]{0x1f436});
        temp.put(":flag-cd:", new int[]{0x1f1e8, 0x1f1e9});
        temp.put(":play_pause:", new int[]{0x23ef});
        temp.put(":articulated_lorry:", new int[]{0x1f69b});
        temp.put(":eye:", new int[]{0x1f441});
        temp.put(":iphone:", new int[]{0x1f4f1});
        temp.put(":flag-tk:", new int[]{0x1f1f9, 0x1f1f0});
        temp.put(":flag-cl:", new int[]{0x1f1e8, 0x1f1f1});
        temp.put(":traffic_light:", new int[]{0x1f6a5});
        temp.put(":star_and_crescent:", new int[]{0x262a});
        temp.put(":oncoming_automobile:", new int[]{0x1f698});
        temp.put(":green_heart:", new int[]{0x1f49a});
        temp.put(":candle:", new int[]{0x1f56f});
        temp.put(":flag-pt:", new int[]{0x1f1f5, 0x1f1f9});
        temp.put(":last_quarter_moon:", new int[]{0x1f317});
        temp.put(":woman:", new int[]{0x1f469});
        temp.put(":calling:", new int[]{0x1f4f2});
        temp.put(":flag-ms:", new int[]{0x1f1f2, 0x1f1f8});
        temp.put(":hammer:", new int[]{0x1f528});
        temp.put(":desert:", new int[]{0x1f3dc});
        temp.put(":aerial_tramway:", new int[]{0x1f6a1});
        temp.put(":star_of_david:", new int[]{0x2721});
        temp.put(":sob:", new int[]{0x1f62d});
        temp.put(":no_mobile_phones:", new int[]{0x1f4f5});
        temp.put(":no_mouth:", new int[]{0x1f636});
        temp.put(":part_alternation_mark:", new int[]{0x303d});
        temp.put(":zap:", new int[]{0x26a1});
        temp.put(":sunglasses:", new int[]{0x1f60e});
        temp.put(":cry:", new int[]{0x1f622});
        temp.put(":mailbox_with_no_mail:", new int[]{0x1f4ed});
        temp.put(":dark_sunglasses:", new int[]{0x1f576});
        temp.put(":flag-bj:", new int[]{0x1f1e7, 0x1f1ef});
        temp.put(":end:", new int[]{0x1f51a});
        temp.put(":flag_ac:", new int[]{0x1f1e6, 0x1f1e8});
        temp.put(":flag-gq:", new int[]{0x1f1ec, 0x1f1f6});
        temp.put(":stadium:", new int[]{0x1f3df});
        temp.put(":heart_exclamation:", new int[]{0x2763});
        temp.put(":notebook:", new int[]{0x1f4d3});
        temp.put(":dash:", new int[]{0x1f4a8});
        temp.put(":white_circle:", new int[]{0x26aa});
        temp.put(":flag_vu:", new int[]{0x1f1fb, 0x1f1fa});
        temp.put(":wind_chime:", new int[]{0x1f390});
        temp.put(":tea:", new int[]{0x1f375});
        temp.put(":waning_gibbous_moon:", new int[]{0x1f316});
        temp.put(":flag-lc:", new int[]{0x1f1f1, 0x1f1e8});
        temp.put(":flag-pw:", new int[]{0x1f1f5, 0x1f1fc});
        temp.put(":drum:", new int[]{0x1f941});
        temp.put(":black_small_square:", new int[]{0x25aa});
        temp.put(":wolf:", new int[]{0x1f43a});
        temp.put(":pisces:", new int[]{0x2653});
        temp.put(":flag_am:", new int[]{0x1f1e6, 0x1f1f2});
        temp.put(":arrow_right:", new int[]{0x27a1});
        temp.put(":handbag:", new int[]{0x1f45c});
        temp.put(":flag-gs:", new int[]{0x1f1ec, 0x1f1f8});
        temp.put(":dancer:", new int[]{0x1f483});
        temp.put(":libra:", new int[]{0x264e});
        temp.put(":running_shirt_with_sash:", new int[]{0x1f3bd});
        temp.put(":womans_hat:", new int[]{0x1f452});
        temp.put(":flag-ng:", new int[]{0x1f1f3, 0x1f1ec});
        temp.put(":flag-ea:", new int[]{0x1f1ea, 0x1f1e6});
        temp.put(":pig:", new int[]{0x1f437});
        temp.put(":ring:", new int[]{0x1f48d});
        temp.put(":arrow_lower_right:", new int[]{0x2198});
        temp.put(":angel:", new int[]{0x1f47c});
        temp.put(":checkered_flag:", new int[]{0x1f3c1});
        temp.put(":bullettrain_side:", new int[]{0x1f684});
        temp.put(":womens:", new int[]{0x1f6ba});
        temp.put(":waxing_crescent_moon:", new int[]{0x1f312});
        temp.put(":ant:", new int[]{0x1f41c});
        temp.put(":flag-im:", new int[]{0x1f1ee, 0x1f1f2});
        temp.put(":spider_web:", new int[]{0x1f578});
        temp.put(":bouquet:", new int[]{0x1f490});
        temp.put(":last_quarter_moon_with_face:", new int[]{0x1f31c});
        temp.put(":dolls:", new int[]{0x1f38e});
        temp.put(":a:", new int[]{0x1f170});
        temp.put(":flag_white:", new int[]{0x1f3f3});
        temp.put(":ship:", new int[]{0x1f6a2});
        temp.put(":sunny:", new int[]{0x2600});
        temp.put(":flag-sa:", new int[]{0x1f1f8, 0x1f1e6});
        temp.put(":smirk_cat:", new int[]{0x1f63c});
        temp.put(":chicken:", new int[]{0x1f414});
        temp.put(":heart_eyes_cat:", new int[]{0x1f63b});
        temp.put(":basketball:", new int[]{0x1f3c0});
        temp.put(":relieved:", new int[]{0x1f60c});
        temp.put(":curly_loop:", new int[]{0x27b0});
        temp.put(":popcorn:", new int[]{0x1f37f});
        temp.put(":flag-sl:", new int[]{0x1f1f8, 0x1f1f1});
        temp.put(":clock6:", new int[]{0x1f555});
        temp.put(":one:", new int[]{0x0031, 0x20e3});
        temp.put(":tongue:", new int[]{0x1f445});
        temp.put(":busstop:", new int[]{0x1f68f});
        temp.put(":flag-ph:", new int[]{0x1f1f5, 0x1f1ed});
        temp.put(":first_quarter_moon_with_face:", new int[]{0x1f31b});
        temp.put(":flag-lb:", new int[]{0x1f1f1, 0x1f1e7});
        temp.put(":department_store:", new int[]{0x1f3ec});
        temp.put(":post_office:", new int[]{0x1f3e3});
        temp.put(":incoming_envelope:", new int[]{0x1f4e8});
        temp.put(":key:", new int[]{0x1f511});
        temp.put(":golf:", new int[]{0x26f3});
        temp.put(":thumbsdown:", new int[]{0x1f44e});
        temp.put(":file_cabinet:", new int[]{0x1f5c4});
        temp.put(":chocolate_bar:", new int[]{0x1f36b});
        temp.put(":page_facing_up:", new int[]{0x1f4c4});
        temp.put(":trolleybus:", new int[]{0x1f68e});
        temp.put(":nine:", new int[]{0x0039, 0x20e3});
        temp.put(":anger:", new int[]{0x1f4a2});
        temp.put(":euro:", new int[]{0x1f4b6});
        temp.put(":wavy_dash:", new int[]{0x3030});
        temp.put(":track_next:", new int[]{0x23ed});
        temp.put(":cookie:", new int[]{0x1f36a});
        temp.put(":bowling:", new int[]{0x1f3b3});
        temp.put(":sandal:", new int[]{0x1f461});
        temp.put(":sagittarius:", new int[]{0x2650});
        temp.put(":link:", new int[]{0x1f517});
        temp.put(":shopping_bags:", new int[]{0x1f6cd});
        temp.put(":gift:", new int[]{0x1f381});
        temp.put(":radio_button:", new int[]{0x1f518});
        temp.put(":motorway:", new int[]{0x1f6e3});
        temp.put(":wheelchair:", new int[]{0x267f});
        temp.put(":white_flower:", new int[]{0x1f4ae});
        temp.put(":u6307:", new int[]{0x1f22f});
        temp.put(":flag-mp:", new int[]{0x1f1f2, 0x1f1f5});
        temp.put(":rat:", new int[]{0x1f400});
        temp.put(":train:", new int[]{0x1f68b});
        temp.put(":arrow_up:", new int[]{0x2b06});
        temp.put(":balloon:", new int[]{0x1f388});
        temp.put(":full_moon_with_face:", new int[]{0x1f31d});
        temp.put(":flag-ml:", new int[]{0x1f1f2, 0x1f1f1});
        temp.put(":hamburger:", new int[]{0x1f354});
        temp.put(":flag-gb:", new int[]{0x1f1ec, 0x1f1e7});
        temp.put(":herb:", new int[]{0x1f33f});
        temp.put(":first_quarter_moon:", new int[]{0x1f313});
        temp.put(":eggplant:", new int[]{0x1f346});
        temp.put(":statue_of_liberty:", new int[]{0x1f5fd});
        temp.put(":egg:", new int[]{0x1f95a});
        temp.put(":pear:", new int[]{0x1f350});
        temp.put(":cold_sweat:", new int[]{0x1f630});
        temp.put(":loudspeaker:", new int[]{0x1f4e2});
        temp.put(":mahjong:", new int[]{0x1f004});
        temp.put(":metro:", new int[]{0x1f687});
        temp.put(":arrow_upper_left:", new int[]{0x2196});
        temp.put(":flag-hr:", new int[]{0x1f1ed, 0x1f1f7});
        temp.put(":flag-no:", new int[]{0x1f1f3, 0x1f1f4});
        temp.put(":flag-do:", new int[]{0x1f1e9, 0x1f1f4});
        temp.put(":white_large_square:", new int[]{0x2b1c});
        temp.put(":hot_pepper:", new int[]{0x1f336});
        temp.put(":flushed:", new int[]{0x1f633});
        temp.put(":dollar:", new int[]{0x1f4b5});
        temp.put(":high_brightness:", new int[]{0x1f506});
        temp.put(":cactus:", new int[]{0x1f335});
        temp.put(":volcano:", new int[]{0x1f30b});
        temp.put(":unlock:", new int[]{0x1f513});
        temp.put(":flag-py:", new int[]{0x1f1f5, 0x1f1fe});
        temp.put(":compression:", new int[]{0x1f5dc});
        temp.put(":flag-il:", new int[]{0x1f1ee, 0x1f1f1});
        temp.put(":hotel:", new int[]{0x1f3e8});
        temp.put(":chipmunk:", new int[]{0x1f43f});
        temp.put(":toilet:", new int[]{0x1f6bd});
        temp.put(":flag-mn:", new int[]{0x1f1f2, 0x1f1f3});
        temp.put(":bamboo:", new int[]{0x1f38d});
        temp.put(":dvd:", new int[]{0x1f4c0});
        temp.put(":flag-cm:", new int[]{0x1f1e8, 0x1f1f2});
        temp.put(":baby_chick:", new int[]{0x1f424});
        temp.put(":family:", new int[]{0x1f46a});
        temp.put(":church:", new int[]{0x26ea});
        temp.put(":flag-cu:", new int[]{0x1f1e8, 0x1f1fa});
        temp.put(":ocean:", new int[]{0x1f30a});
        temp.put(":anger_right:", new int[]{0x1f5ef});
        temp.put(":mag:", new int[]{0x1f50d});
        temp.put(":bicyclist:", new int[]{0x1f6b4});
        temp.put(":flag-cv:", new int[]{0x1f1e8, 0x1f1fb});
        temp.put(":hourglass_flowing_sand:", new int[]{0x23f3});
        temp.put(":open_file_folder:", new int[]{0x1f4c2});
        temp.put(":repeat_one:", new int[]{0x1f502});
        temp.put(":arrow_double_up:", new int[]{0x23eb});
        temp.put(":id:", new int[]{0x1f194});
        temp.put(":melon:", new int[]{0x1f348});
        temp.put(":boar:", new int[]{0x1f417});
        temp.put(":flag-td:", new int[]{0x1f1f9, 0x1f1e9});
        temp.put(":flag-sv:", new int[]{0x1f1f8, 0x1f1fb});
        temp.put(":cake:", new int[]{0x1f370});
        temp.put(":dolphin:", new int[]{0x1f42c});
        temp.put(":joy_cat:", new int[]{0x1f639});
        temp.put(":new_moon:", new int[]{0x1f311});
        temp.put(":tennis:", new int[]{0x1f3be});
        temp.put(":golfer:", new int[]{0x1f3cc});
        temp.put(":flag-bw:", new int[]{0x1f1e7, 0x1f1fc});
        temp.put(":bride_with_veil:", new int[]{0x1f470});
        temp.put(":writing_hand:", new int[]{0x270d});
        temp.put(":rice_cracker:", new int[]{0x1f358});
        temp.put(":clock130:", new int[]{0x1f55c});
        temp.put(":expressionless:", new int[]{0x1f611});
        temp.put(":banana:", new int[]{0x1f34c});
        temp.put(":mens:", new int[]{0x1f6b9});
        temp.put(":water_buffalo:", new int[]{0x1f403});
        temp.put(":flag-br:", new int[]{0x1f1e7, 0x1f1f7});
        temp.put(":flag-as:", new int[]{0x1f1e6, 0x1f1f8});
        temp.put(":flag-ly:", new int[]{0x1f1f1, 0x1f1fe});
        temp.put(":abcd:", new int[]{0x1f521});
        temp.put(":pensive:", new int[]{0x1f614});
        temp.put(":flag-bv:", new int[]{0x1f1e7, 0x1f1fb});
        temp.put(":clock5:", new int[]{0x1f554});
        temp.put(":triumph:", new int[]{0x1f624});
        temp.put(":thermometer:", new int[]{0x1f321});
        temp.put(":house_with_garden:", new int[]{0x1f3e1});
        temp.put(":clock930:", new int[]{0x1f564});
        temp.put(":truck:", new int[]{0x1f69a});
        temp.put(":chart:", new int[]{0x1f4b9});
        temp.put(":flag-ch:", new int[]{0x1f1e8, 0x1f1ed});
        temp.put(":rabbit:", new int[]{0x1f430});
        temp.put(":star:", new int[]{0x2b50});
        temp.put(":rolling_eyes:", new int[]{0x1f644});
        temp.put(":fearful:", new int[]{0x1f628});
        temp.put(":gear:", new int[]{0x2699});
        temp.put(":cool:", new int[]{0x1f192});
        temp.put(":flag-mv:", new int[]{0x1f1f2, 0x1f1fb});
        temp.put(":flag-ge:", new int[]{0x1f1ec, 0x1f1ea});
        temp.put(":repeat:", new int[]{0x1f501});
        temp.put(":waning_crescent_moon:", new int[]{0x1f318});
        temp.put(":radio:", new int[]{0x1f4fb});
        temp.put(":flag_yt:", new int[]{0x1f1fe, 0x1f1f9});
        temp.put(":raised_hands:", new int[]{0x1f64c});
        temp.put(":earth_americas:", new int[]{0x1f30e});
        temp.put(":currency_exchange:", new int[]{0x1f4b1});
        temp.put(":flag-gn:", new int[]{0x1f1ec, 0x1f1f3});
        temp.put(":blue_heart:", new int[]{0x1f499});
        temp.put(":flag-gp:", new int[]{0x1f1ec, 0x1f1f5});
        temp.put(":yum:", new int[]{0x1f60b});
        temp.put(":cd:", new int[]{0x1f4bf});
        temp.put(":hibiscus:", new int[]{0x1f33a});
        temp.put(":flag-cc:", new int[]{0x1f1e8, 0x1f1e8});
        temp.put(":flag-dj:", new int[]{0x1f1e9, 0x1f1ef});
        temp.put(":abc:", new int[]{0x1f524});
        temp.put(":sunflower:", new int[]{0x1f33b});
        temp.put(":custard:", new int[]{0x1f36e});
        temp.put(":small_blue_diamond:", new int[]{0x1f539});
        temp.put(":candy:", new int[]{0x1f36c});
        temp.put(":flag-cn:", new int[]{0x1f1e8, 0x1f1f3});
        temp.put(":notes:", new int[]{0x1f3b6});
        temp.put(":tram:", new int[]{0x1f68a});
        temp.put(":flag-ne:", new int[]{0x1f1f3, 0x1f1ea});
        temp.put(":taco:", new int[]{0x1f32e});
        temp.put(":black_medium_square:", new int[]{0x25fc});
        temp.put(":hatching_chick:", new int[]{0x1f423});
        temp.put(":koala:", new int[]{0x1f428});
        temp.put(":flag-si:", new int[]{0x1f1f8, 0x1f1ee});
        temp.put(":beginner:", new int[]{0x1f530});
        temp.put(":shield:", new int[]{0x1f6e1});
        temp.put(":tada:", new int[]{0x1f389});
        temp.put(":fire:", new int[]{0x1f525});
        temp.put(":lock:", new int[]{0x1f512});
        temp.put(":computer:", new int[]{0x1f4bb});
        temp.put(":vertical_traffic_light:", new int[]{0x1f6a6});
        temp.put(":calendar:", new int[]{0x1f4c6});
        temp.put(":flag-lu:", new int[]{0x1f1f1, 0x1f1fa});
        temp.put(":om_symbol:", new int[]{0x1f549});
        temp.put(":flag-ba:", new int[]{0x1f1e7, 0x1f1e6});
        temp.put(":flag-be:", new int[]{0x1f1e7, 0x1f1ea});
        temp.put(":skier:", new int[]{0x26f7});
        temp.put(":point_up_2:", new int[]{0x1f446});
        temp.put(":eyes:", new int[]{0x1f440});
        temp.put(":seedling:", new int[]{0x1f331});
        temp.put(":flag-dg:", new int[]{0x1f1e9, 0x1f1ec});
        temp.put(":ok:", new int[]{0x1f197});
        temp.put(":symbols:", new int[]{0x1f523});
        temp.put(":dango:", new int[]{0x1f361});
        temp.put(":camera_with_flash:", new int[]{0x1f4f8});
        temp.put(":athletic_shoe:", new int[]{0x1f45f});
        temp.put(":mobile_phone_off:", new int[]{0x1f4f4});
        temp.put(":wind_blowing_face:", new int[]{0x1f32c});
        temp.put(":amphora:", new int[]{0x1f3fa});
        temp.put(":globe_with_meridians:", new int[]{0x1f310});
        temp.put(":money_with_wings:", new int[]{0x1f4b8});
        temp.put(":sun_with_face:", new int[]{0x1f31e});
        temp.put(":flag-nc:", new int[]{0x1f1f3, 0x1f1e8});
        temp.put(":girl:", new int[]{0x1f467});
        temp.put(":cancer:", new int[]{0x264b});
        temp.put(":camel:", new int[]{0x1f42b});
        temp.put(":jeans:", new int[]{0x1f456});
        temp.put(":flag-nf:", new int[]{0x1f1f3, 0x1f1eb});
        temp.put(":flag-sx:", new int[]{0x1f1f8, 0x1f1fd});
        temp.put(":construction:", new int[]{0x1f6a7});
        temp.put(":flag-mh:", new int[]{0x1f1f2, 0x1f1ed});
        temp.put(":kissing_closed_eyes:", new int[]{0x1f61a});
        temp.put(":umbrella:", new int[]{0x2614});
        temp.put(":grey_question:", new int[]{0x2754});
        temp.put(":four_leaf_clover:", new int[]{0x1f340});
        temp.put(":shaved_ice:", new int[]{0x1f367});
        temp.put(":flag-ca:", new int[]{0x1f1e8, 0x1f1e6});
        temp.put(":closed_book:", new int[]{0x1f4d5});
        temp.put(":flag_ye:", new int[]{0x1f1fe, 0x1f1ea});
        temp.put(":nerd:", new int[]{0x1f913});
        temp.put(":movie_camera:", new int[]{0x1f3a5});
        temp.put(":flag-ma:", new int[]{0x1f1f2, 0x1f1e6});
        temp.put(":clock3:", new int[]{0x1f552});
        temp.put(":school:", new int[]{0x1f3eb});
        temp.put(":ghost:", new int[]{0x1f47b});
        temp.put(":spades:", new int[]{0x2660});
        temp.put(":fishing_pole_and_fish:", new int[]{0x1f3a3});
        temp.put(":bookmark_tabs:", new int[]{0x1f4d1});
        temp.put(":rosette:", new int[]{0x1f3f5});
        temp.put(":heavy_check_mark:", new int[]{0x2714});
        temp.put(":flag-at:", new int[]{0x1f1e6, 0x1f1f9});
        temp.put(":closed_lock_with_key:", new int[]{0x1f510});
        temp.put(":ice_skate:", new int[]{0x26f8});
        temp.put(":non-potable_water:", new int[]{0x1f6b1});
        temp.put(":o2:", new int[]{0x1f17e});
        temp.put(":sunrise_over_mountains:", new int[]{0x1f304});
        temp.put(":grinning:", new int[]{0x1f600});
        temp.put(":u6e80:", new int[]{0x1f235});
        temp.put(":yellow_heart:", new int[]{0x1f49b});
        temp.put(":scissors:", new int[]{0x2702});
        temp.put(":flag-li:", new int[]{0x1f1f1, 0x1f1ee});
        temp.put(":flag-ax:", new int[]{0x1f1e6, 0x1f1fd});
        temp.put(":apple:", new int[]{0x1f34e});
        temp.put(":tropical_fish:", new int[]{0x1f420});
        temp.put(":card_index:", new int[]{0x1f4c7});
        temp.put(":surfer:", new int[]{0x1f3c4});
        temp.put(":satellite:", new int[]{0x1f4e1});
        temp.put(":nut_and_bolt:", new int[]{0x1f529});
        temp.put(":older_man:", new int[]{0x1f474});
        temp.put(":flag-sk:", new int[]{0x1f1f8, 0x1f1f0});
        temp.put(":black_heart:", new int[]{0x1f5a4});
        temp.put(":flag_ae:", new int[]{0x1f1e6, 0x1f1ea});
        temp.put(":chart_with_upwards_trend:", new int[]{0x1f4c8});
        temp.put(":flag-jp:", new int[]{0x1f1ef, 0x1f1f5});
        temp.put(":office:", new int[]{0x1f3e2});
        temp.put(":cross:", new int[]{0x271d});
        temp.put(":fax:", new int[]{0x1f4e0});
        temp.put(":heart_eyes:", new int[]{0x1f60d});
        temp.put(":heavy_multiplication_x:", new int[]{0x2716});
        temp.put(":cherry_blossom:", new int[]{0x1f338});
        temp.put(":sheep:", new int[]{0x1f411});
        temp.put(":police_car:", new int[]{0x1f693});
        temp.put(":flag-pl:", new int[]{0x1f1f5, 0x1f1f1});
        temp.put(":flag-us:", new int[]{0x1f1fa, 0x1f1f8});
        temp.put(":mega:", new int[]{0x1f4e3});
        temp.put(":snowflake:", new int[]{0x2744});
        temp.put(":lips:", new int[]{0x1f444});
        temp.put(":syringe:", new int[]{0x1f489});
        temp.put(":electric_plug:", new int[]{0x1f50c});
        temp.put(":synagogue:", new int[]{0x1f54d});
        temp.put(":no_entry:", new int[]{0x26d4});
        temp.put(":arrow_down:", new int[]{0x2b07});
        temp.put(":circus_tent:", new int[]{0x1f3aa});
        temp.put(":spider:", new int[]{0x1f577});
        temp.put(":scorpius:", new int[]{0x264f});
        temp.put(":clock1230:", new int[]{0x1f567});
        temp.put(":do_not_litter:", new int[]{0x1f6af});
        temp.put(":gun:", new int[]{0x1f52b});
        temp.put(":ox:", new int[]{0x1f402});
        temp.put(":upside_down:", new int[]{0x1f643});
        temp.put(":flag-sg:", new int[]{0x1f1f8, 0x1f1ec});
        temp.put(":couplekiss:", new int[]{0x1f48f});
        temp.put(":princess:", new int[]{0x1f478});
        temp.put(":moyai:", new int[]{0x1f5ff});
        temp.put(":red_circle:", new int[]{0x1f534});
        temp.put(":fuelpump:", new int[]{0x26fd});
        temp.put(":loud_sound:", new int[]{0x1f50a});
        temp.put(":wink:", new int[]{0x1f609});
        temp.put(":dart:", new int[]{0x1f3af});
        temp.put(":tropical_drink:", new int[]{0x1f379});
        temp.put(":flag-gg:", new int[]{0x1f1ec, 0x1f1ec});
        temp.put(":left_right_arrow:", new int[]{0x2194});
        temp.put(":aquarius:", new int[]{0x2652});
        temp.put(":ram:", new int[]{0x1f40f});
        temp.put(":maple_leaf:", new int[]{0x1f341});
        temp.put(":high_heel:", new int[]{0x1f460});
        temp.put(":icecream:", new int[]{0x1f366});
        temp.put(":blossom:", new int[]{0x1f33c});
        temp.put(":flag_ad:", new int[]{0x1f1e6, 0x1f1e9});
        temp.put(":bear:", new int[]{0x1f43b});
        temp.put(":soccer:", new int[]{0x26bd});
        temp.put(":foggy:", new int[]{0x1f301});
        temp.put(":flag-ro:", new int[]{0x1f1f7, 0x1f1f4});
        temp.put(":flag-sz:", new int[]{0x1f1f8, 0x1f1ff});
        temp.put(":flag-cp:", new int[]{0x1f1e8, 0x1f1f5});
        temp.put(":minidisc:", new int[]{0x1f4bd});
        temp.put(":football:", new int[]{0x1f3c8});
        temp.put(":construction_worker:", new int[]{0x1f477});
        temp.put(":carousel_horse:", new int[]{0x1f3a0});
        temp.put(":b:", new int[]{0x1f171});
        temp.put(":beer:", new int[]{0x1f37a});
        temp.put(":flag_af:", new int[]{0x1f1e6, 0x1f1eb});
        temp.put(":us:", new int[]{0x1f1fa});
        temp.put(":ticket:", new int[]{0x1f3ab});
        temp.put(":sleepy:", new int[]{0x1f62a});
        temp.put(":clipboard:", new int[]{0x1f4cb});
        temp.put(":shamrock:", new int[]{0x2618});
        temp.put(":flag_za:", new int[]{0x1f1ff, 0x1f1e6});
        temp.put(":flag-gd:", new int[]{0x1f1ec, 0x1f1e9});
        temp.put(":camera:", new int[]{0x1f4f7});
        temp.put(":european_post_office:", new int[]{0x1f3e4});
        temp.put(":arrow_forward:", new int[]{0x25b6});
        temp.put(":smile:", new int[]{0x1f604});
        temp.put(":flag-in:", new int[]{0x1f1ee, 0x1f1f3});
        temp.put(":flag-iq:", new int[]{0x1f1ee, 0x1f1f6});
        temp.put(":vibration_mode:", new int[]{0x1f4f3});
        temp.put(":pig2:", new int[]{0x1f416});
        temp.put(":o:", new int[]{0x2b55});
        temp.put(":name_badge:", new int[]{0x1f4db});
        temp.put(":sparkle:", new int[]{0x2747});
        temp.put(":pushpin:", new int[]{0x1f4cc});
        temp.put(":monorail:", new int[]{0x1f69d});
        temp.put(":exclamation:", new int[]{0x2757});
        temp.put(":flag-mz:", new int[]{0x1f1f2, 0x1f1ff});
        temp.put(":earth_africa:", new int[]{0x1f30d});
        temp.put(":cherries:", new int[]{0x1f352});
        temp.put(":wedding:", new int[]{0x1f492});
        temp.put(":peach:", new int[]{0x1f351});
        temp.put(":point_up:", new int[]{0x261d});
        temp.put(":inbox_tray:", new int[]{0x1f4e5});
        temp.put(":new:", new int[]{0x1f195});
        temp.put(":flag-sc:", new int[]{0x1f1f8, 0x1f1e8});
        temp.put(":ribbon:", new int[]{0x1f380});
        temp.put(":flag-dk:", new int[]{0x1f1e9, 0x1f1f0});
        temp.put(":musical_score:", new int[]{0x1f3bc});
        temp.put(":flag-ki:", new int[]{0x1f1f0, 0x1f1ee});
        temp.put(":trident:", new int[]{0x1f531});
        temp.put(":scream:", new int[]{0x1f631});
        temp.put(":pizza:", new int[]{0x1f355});
        temp.put(":eight:", new int[]{0x0038, 0x20e3});
        temp.put(":flag-mr:", new int[]{0x1f1f2, 0x1f1f7});
        temp.put(":taurus:", new int[]{0x2649});
        temp.put(":information_source:", new int[]{0x2139});
        temp.put(":flag-km:", new int[]{0x1f1f0, 0x1f1f2});
        temp.put(":crystal_ball:", new int[]{0x1f52e});
        temp.put(":flag-sr:", new int[]{0x1f1f8, 0x1f1f7});
        temp.put(":flag-de:", new int[]{0x1f1e9, 0x1f1ea});
        temp.put(":ledger:", new int[]{0x1f4d2});
        temp.put(":ok_woman:", new int[]{0x1f646});
        temp.put(":flag-pe:", new int[]{0x1f1f5, 0x1f1ea});
        temp.put(":tiger:", new int[]{0x1f42f});
        temp.put(":runner:", new int[]{0x1f3c3});
        temp.put(":sushi:", new int[]{0x1f363});
        temp.put(":flag-ve:", new int[]{0x1f1fb, 0x1f1ea});
        temp.put(":books:", new int[]{0x1f4da});
        temp.put(":santa:", new int[]{0x1f385});
        temp.put(":crying_cat_face:", new int[]{0x1f63f});
        temp.put(":flag-cy:", new int[]{0x1f1e8, 0x1f1fe});
        temp.put(":flag-my:", new int[]{0x1f1f2, 0x1f1fe});
        temp.put(":flag-ni:", new int[]{0x1f1f3, 0x1f1ee});
        temp.put(":curry:", new int[]{0x1f35b});
        temp.put(":cat:", new int[]{0x1f431});
        temp.put(":person_with_blond_hair:", new int[]{0x1f471});
        temp.put(":8ball:", new int[]{0x1f3b1});
        temp.put(":station:", new int[]{0x1f689});
        temp.put(":pouting_cat:", new int[]{0x1f63e});
        temp.put(":kaaba:", new int[]{0x1f54b});
        temp.put(":arrow_heading_down:", new int[]{0x2935});
        temp.put(":volleyball:", new int[]{0x1f3d0});
        temp.put(":briefcase:", new int[]{0x1f4bc});
        temp.put(":mag_right:", new int[]{0x1f50e});
        temp.put(":busts_in_silhouette:", new int[]{0x1f465});
        temp.put(":flag-pk:", new int[]{0x1f1f5, 0x1f1f0});
        temp.put(":whale2:", new int[]{0x1f40b});
        temp.put(":leo:", new int[]{0x264c});
        temp.put(":stuck_out_tongue:", new int[]{0x1f61b});
        temp.put(":arrow_double_down:", new int[]{0x23ec});
        temp.put(":flag-bi:", new int[]{0x1f1e7, 0x1f1ee});
        temp.put(":flag-tz:", new int[]{0x1f1f9, 0x1f1ff});
        temp.put(":flag-fm:", new int[]{0x1f1eb, 0x1f1f2});
        temp.put(":grin:", new int[]{0x1f601});
        temp.put(":u6708:", new int[]{0x1f237});
        temp.put(":flag-tc:", new int[]{0x1f1f9, 0x1f1e8});
        temp.put(":middle_finger:", new int[]{0x1f595});
        temp.put(":heart:", new int[]{0x2764});
        temp.put(":level_slider:", new int[]{0x1f39a});
        temp.put(":rotating_light:", new int[]{0x1f6a8});
        temp.put(":flag-nu:", new int[]{0x1f1f3, 0x1f1fa});
        temp.put(":champagne:", new int[]{0x1f37e});
        temp.put(":floppy_disk:", new int[]{0x1f4be});
        temp.put("*", new int[]{});
        temp.put(":flag_ai:", new int[]{0x1f1e6, 0x1f1ee});
        temp.put(":wave:", new int[]{0x1f44b});
        temp.put(":warning:", new int[]{0x26a0});
        temp.put(":lion_face:", new int[]{0x1f981});
        temp.put(":saxophone:", new int[]{0x1f3b7});
        temp.put(":flag-hn:", new int[]{0x1f1ed, 0x1f1f3});
        temp.put(":flag-ie:", new int[]{0x1f1ee, 0x1f1ea});
        temp.put(":fish_cake:", new int[]{0x1f365});
        temp.put(":heavy_division_sign:", new int[]{0x2797});
        temp.put(":mailbox:", new int[]{0x1f4eb});
        temp.put(":confetti_ball:", new int[]{0x1f38a});
        temp.put(":clap:", new int[]{0x1f44f});
        temp.put(":monkey_face:", new int[]{0x1f435});
        temp.put(":night_with_stars:", new int[]{0x1f303});
        temp.put(":scroll:", new int[]{0x1f4dc});
        temp.put(":beach_umbrella:", new int[]{0x26f1});
        temp.put(":hotsprings:", new int[]{0x2668});
        temp.put(":baby:", new int[]{0x1f476});
        temp.put(":house:", new int[]{0x1f3e0});
        temp.put(":postal_horn:", new int[]{0x1f4ef});
        temp.put(":dancers:", new int[]{0x1f46f});
        temp.put(":mountain_bicyclist:", new int[]{0x1f6b5});
        temp.put(":left_luggage:", new int[]{0x1f6c5});
        temp.put(":helicopter:", new int[]{0x1f681});
        temp.put(":dizzy_face:", new int[]{0x1f635});
        temp.put(":flag-pn:", new int[]{0x1f1f5, 0x1f1f3});
        temp.put(":back:", new int[]{0x1f519});
        temp.put(":credit_card:", new int[]{0x1f4b3});
        temp.put(":clock730:", new int[]{0x1f562});
        temp.put(":suspension_railway:", new int[]{0x1f69f});
        temp.put(":pray:", new int[]{0x1f64f});
        temp.put(":feet:", new int[]{0x1f43e});
        temp.put(":oncoming_taxi:", new int[]{0x1f696});
        temp.put(":grapes:", new int[]{0x1f347});
        temp.put(":crossed_flags:", new int[]{0x1f38c});
        temp.put(":tent:", new int[]{0x26fa});
        temp.put(":flag-fk:", new int[]{0x1f1eb, 0x1f1f0});
        temp.put(":ok_hand:", new int[]{0x1f44c});
        temp.put(":flag-la:", new int[]{0x1f1f1, 0x1f1e6});
        temp.put(":arrow_up_small:", new int[]{0x1f53c});
        temp.put(":strawberry:", new int[]{0x1f353});
        temp.put(":orange_book:", new int[]{0x1f4d9});
        temp.put(":small_orange_diamond:", new int[]{0x1f538});
        temp.put(":swimmer:", new int[]{0x1f3ca});
        temp.put(":flag-tm:", new int[]{0x1f1f9, 0x1f1f2});
        temp.put(":flag-gr:", new int[]{0x1f1ec, 0x1f1f7});
        temp.put(":atom:", new int[]{0x269b});
        temp.put(":snake:", new int[]{0x1f40d});
        temp.put(":tokyo_tower:", new int[]{0x1f5fc});
        temp.put(":sos:", new int[]{0x1f198});
        temp.put(":flag-mu:", new int[]{0x1f1f2, 0x1f1fa});
        temp.put(":heartbeat:", new int[]{0x1f493});
        temp.put(":flag-fr:", new int[]{0x1f1eb, 0x1f1f7});
        temp.put(":flag_xk:", new int[]{0x1f1fd, 0x1f1f0});
        temp.put(":clock8:", new int[]{0x1f557});
        temp.put(":christmas_tree:", new int[]{0x1f384});
        temp.put(":diamonds:", new int[]{0x2666});
        temp.put(":postbox:", new int[]{0x1f4ee});
        temp.put(":wastebasket:", new int[]{0x1f5d1});
        temp.put(":camping:", new int[]{0x1f3d5});
        temp.put(":flag-pg:", new int[]{0x1f1f5, 0x1f1ec});
        temp.put(":heavy_plus_sign:", new int[]{0x2795});
        temp.put(":sparkler:", new int[]{0x1f387});
        temp.put(":dromedary_camel:", new int[]{0x1f42a});
        temp.put(":flag-ci:", new int[]{0x1f1e8, 0x1f1ee});
        temp.put(":two_women_holding_hands:", new int[]{0x1f46d});
        temp.put(":rainbow:", new int[]{0x1f308});
        temp.put(":mosque:", new int[]{0x1f54c});
        temp.put(":flag-by:", new int[]{0x1f1e7, 0x1f1fe});
        temp.put(":signal_strength:", new int[]{0x1f4f6});
        temp.put(":grey_exclamation:", new int[]{0x2755});
        temp.put(":sleeping_accommodation:", new int[]{0x1f6cc});
        temp.put(":shirt:", new int[]{0x1f455});
        temp.put(":flag-st:", new int[]{0x1f1f8, 0x1f1f9});
        temp.put(":flag-so:", new int[]{0x1f1f8, 0x1f1f4});
        temp.put(":flag-tg:", new int[]{0x1f1f9, 0x1f1ec});
        temp.put(":potable_water:", new int[]{0x1f6b0});
        temp.put(":new_moon_with_face:", new int[]{0x1f31a});
        temp.put(":date:", new int[]{0x1f4c5});
        temp.put(":flag-eu:", new int[]{0x1f1ea, 0x1f1fa});
        temp.put(":mouse2:", new int[]{0x1f401});
        temp.put(":frowning:", new int[]{0x1f626});
        temp.put(":arrow_left:", new int[]{0x2b05});
        temp.put(":flag-aq:", new int[]{0x1f1e6, 0x1f1f6});
        temp.put(":flag-mo:", new int[]{0x1f1f2, 0x1f1f4});
        temp.put(":bangbang:", new int[]{0x203c});
        temp.put(":kissing:", new int[]{0x1f617});
        temp.put(":flag-re:", new int[]{0x1f1f7, 0x1f1ea});
        temp.put(":pouch:", new int[]{0x1f45d});
        temp.put(":sparkling_heart:", new int[]{0x1f496});
        temp.put(":x:", new int[]{0x274c});
        temp.put(":clock1130:", new int[]{0x1f566});
        temp.put(":notebook_with_decorative_cover:", new int[]{0x1f4d4});
        temp.put(":tiger2:", new int[]{0x1f405});
        temp.put(":sleeping:", new int[]{0x1f634});
        temp.put(":flag-kr:", new int[]{0x1f1f0, 0x1f1f7});
        temp.put(":thought_balloon:", new int[]{0x1f4ad});
        temp.put(":gemini:", new int[]{0x264a});
        temp.put(":violin:", new int[]{0x1f3bb});
        temp.put(":speaker:", new int[]{0x1f508});
        temp.put(":scales:", new int[]{0x2696});
        temp.put(":revolving_hearts:", new int[]{0x1f49e});
        temp.put(":no_good:", new int[]{0x1f645});
        temp.put(":black_circle:", new int[]{0x26ab});
        temp.put(":flag-aw:", new int[]{0x1f1e6, 0x1f1fc});
        temp.put(":door:", new int[]{0x1f6aa});
        temp.put(":flag-cg:", new int[]{0x1f1e8, 0x1f1ec});
        temp.put(":lollipop:", new int[]{0x1f36d});
        temp.put(":mailbox_with_mail:", new int[]{0x1f4ec});
        temp.put(":flower_playing_cards:", new int[]{0x1f3b4});
        temp.put(":tangerine:", new int[]{0x1f34a});
        temp.put(":jack_o_lantern:", new int[]{0x1f383});
        temp.put(":u7a7a:", new int[]{0x1f233});
        temp.put(":mountain_cableway:", new int[]{0x1f6a0});
        temp.put(":orthodox_cross:", new int[]{0x2626});
        temp.put(":rose:", new int[]{0x1f339});
        temp.put(":comet:", new int[]{0x2604});
        temp.put(":eight_spoked_asterisk:", new int[]{0x2733});
        temp.put(":flag-eg:", new int[]{0x1f1ea, 0x1f1ec});
        temp.put(":space_invader:", new int[]{0x1f47e});
        temp.put(":watermelon:", new int[]{0x1f349});
        temp.put(":boy:", new int[]{0x1f466});
        temp.put(":rowboat:", new int[]{0x1f6a3});
        temp.put(":love_hotel:", new int[]{0x1f3e9});
        temp.put(":baseball:", new int[]{0x26be});
        temp.put(":flag-ta:", new int[]{0x1f1f9, 0x1f1e6});
        temp.put(":flag-er:", new int[]{0x1f1ea, 0x1f1f7});
        temp.put(":flag-co:", new int[]{0x1f1e8, 0x1f1f4});
        temp.put(":anchor:", new int[]{0x2693});
        temp.put(":leaves:", new int[]{0x1f343});
        temp.put(":nose:", new int[]{0x1f443});
        temp.put(":snail:", new int[]{0x1f40c});
        temp.put(":pill:", new int[]{0x1f48a});
        temp.put(":older_woman:", new int[]{0x1f475});
        temp.put(":burrito:", new int[]{0x1f32f});
        temp.put(":clock830:", new int[]{0x1f563});
        temp.put(":city_sunset:", new int[]{0x1f307});
        temp.put(":classical_building:", new int[]{0x1f3db});
        temp.put(":newspaper:", new int[]{0x1f4f0});
        temp.put(":arrows_clockwise:", new int[]{0x1f503});
        temp.put(":green_apple:", new int[]{0x1f34f});
        temp.put(":capital_abcd:", new int[]{0x1f520});
        temp.put(":bed:", new int[]{0x1f6cf});
        temp.put(":flag-gh:", new int[]{0x1f1ec, 0x1f1ed});
        temp.put(":no_pedestrians:", new int[]{0x1f6b7});
        temp.put(":bar_chart:", new int[]{0x1f4ca});
        temp.put(":elephant:", new int[]{0x1f418});
        temp.put(":black_nib:", new int[]{0x2712});
        temp.put(":bow:", new int[]{0x1f647});
        temp.put(":flag-nl:", new int[]{0x1f1f3, 0x1f1f1});
        temp.put(":telephone_receiver:", new int[]{0x1f4de});
        temp.put(":sweet_potato:", new int[]{0x1f360});
        temp.put(":flag-ec:", new int[]{0x1f1ea, 0x1f1e8});
        temp.put(":flag-bm:", new int[]{0x1f1e7, 0x1f1f2});
        temp.put(":four:", new int[]{0x0034, 0x20e3});
        temp.put(":arrows_counterclockwise:", new int[]{0x1f504});
        temp.put(":flag-au:", new int[]{0x1f1e6, 0x1f1fa});
        temp.put(":flag-gu:", new int[]{0x1f1ec, 0x1f1fa});
        temp.put(":rugby_football:", new int[]{0x1f3c9});
        temp.put(":stuck_out_tongue_closed_eyes:", new int[]{0x1f61d});
        temp.put(":moneybag:", new int[]{0x1f4b0});
        temp.put(":performing_arts:", new int[]{0x1f3ad});
        temp.put(":clock630:", new int[]{0x1f561});
        temp.put(":musical_note:", new int[]{0x1f3b5});
        temp.put(":pencil2:", new int[]{0x270f});
        temp.put(":rice_scene:", new int[]{0x1f391});
        temp.put(":point_right:", new int[]{0x1f449});
        temp.put(":railway_track:", new int[]{0x1f6e4});
        temp.put(":horse_racing:", new int[]{0x1f3c7});
        temp.put(":flag-ar:", new int[]{0x1f1e6, 0x1f1f7});
        temp.put(":triangular_flag_on_post:", new int[]{0x1f6a9});
        temp.put(":deciduous_tree:", new int[]{0x1f333});
        temp.put(":black_large_square:", new int[]{0x2b1b});
        temp.put(":flag-mf:", new int[]{0x1f1f2, 0x1f1eb});
        temp.put(":flag-rs:", new int[]{0x1f1f7, 0x1f1f8});
        temp.put(":keycap_ten:", new int[]{0x1f51f});
        temp.put(":two_hearts:", new int[]{0x1f495});
        temp.put(":penguin:", new int[]{0x1f427});
        temp.put(":clock1030:", new int[]{0x1f565});
        temp.put(":flag-bs:", new int[]{0x1f1e7, 0x1f1f8});
        temp.put(":flag-hk:", new int[]{0x1f1ed, 0x1f1f0});
        temp.put(":flag-gf:", new int[]{0x1f1ec, 0x1f1eb});
        temp.put(":open_mouth:", new int[]{0x1f62e});
        temp.put(":battery:", new int[]{0x1f50b});
        temp.put(":flag-gw:", new int[]{0x1f1ec, 0x1f1fc});
        temp.put(":ng:", new int[]{0x1f196});
        temp.put(":flag-tr:", new int[]{0x1f1f9, 0x1f1f7});
        temp.put(":flag_zw:", new int[]{0x1f1ff, 0x1f1fc});
        temp.put(":ballot_box:", new int[]{0x1f5f3});
        temp.put(":flag-mx:", new int[]{0x1f1f2, 0x1f1fd});
        temp.put(":mountain_railway:", new int[]{0x1f69e});
        temp.put(":thumbsup:", new int[]{0x1f44d});
        temp.put(":medal:", new int[]{0x1f3c5});
        temp.put(":alien:", new int[]{0x1f47d});
        temp.put(":flag-sd:", new int[]{0x1f1f8, 0x1f1e9});
        temp.put(":oncoming_police_car:", new int[]{0x1f694});
        temp.put(":flag-sm:", new int[]{0x1f1f8, 0x1f1f2});
        temp.put(":interrobang:", new int[]{0x2049});
        temp.put(":blue_circle:", new int[]{0x1f535});
        temp.put(":ear_of_rice:", new int[]{0x1f33e});
        temp.put(":black_joker:", new int[]{0x1f0cf});
        temp.put(":telescope:", new int[]{0x1f52d});
        temp.put(":no_bicycles:", new int[]{0x1f6b3});
        temp.put(":crescent_moon:", new int[]{0x1f319});
        temp.put(":stopwatch:", new int[]{0x23f1});
        temp.put(":purple_heart:", new int[]{0x1f49c});
        temp.put(":flag-hm:", new int[]{0x1f1ed, 0x1f1f2});
        temp.put(":flag-bo:", new int[]{0x1f1e7, 0x1f1f4});
        temp.put(":bike:", new int[]{0x1f6b2});
        temp.put(":hamster:", new int[]{0x1f439});
        temp.put(":track_previous:", new int[]{0x23ee});
        temp.put(":no_entry_sign:", new int[]{0x1f6ab});
        temp.put(":hospital:", new int[]{0x1f3e5});
        temp.put(":kissing_smiling_eyes:", new int[]{0x1f619});
        temp.put(":baby_bottle:", new int[]{0x1f37c});
        temp.put(":nail_care:", new int[]{0x1f485});
        temp.put(":top:", new int[]{0x1f51d});
        temp.put(":flag-fj:", new int[]{0x1f1eb, 0x1f1ef});
        temp.put(":earth_asia:", new int[]{0x1f30f});
        temp.put(":crocodile:", new int[]{0x1f40a});
        temp.put(":flag-et:", new int[]{0x1f1ea, 0x1f1f9});
        temp.put(":shell:", new int[]{0x1f41a});
        temp.put(":outbox_tray:", new int[]{0x1f4e4});
        temp.put(":straight_ruler:", new int[]{0x1f4cf});
        temp.put(":footprints:", new int[]{0x1f463});
        temp.put(":large_blue_diamond:", new int[]{0x1f537});
        temp.put(":rooster:", new int[]{0x1f413});
        temp.put(":goat:", new int[]{0x1f410});
        temp.put(":clock7:", new int[]{0x1f556});
        temp.put(":bomb:", new int[]{0x1f4a3});
        temp.put(":hash:", new int[]{0x0023, 0x20e3});
        temp.put(":hatched_chick:", new int[]{0x1f425});
        temp.put(":tractor:", new int[]{0x1f69c});
        temp.put(":flag-rw:", new int[]{0x1f1f7, 0x1f1fc});
        temp.put(":stuck_out_tongue_winking_eye:", new int[]{0x1f61c});
        temp.put(":rewind:", new int[]{0x23ea});
        temp.put(":yin_yang:", new int[]{0x262f});
        temp.put(":ramen:", new int[]{0x1f35c});
        temp.put(":trackball:", new int[]{0x1f5b2});
        temp.put(":flag-kn:", new int[]{0x1f1f0, 0x1f1f3});
        temp.put(":prayer_beads:", new int[]{0x1f4ff});
        temp.put(":bulb:", new int[]{0x1f4a1});
        temp.put(":turkey:", new int[]{0x1f983});
        temp.put(":speedboat:", new int[]{0x1f6a4});
        temp.put(":neutral_face:", new int[]{0x1f610});
        temp.put(":bell:", new int[]{0x1f514});
        temp.put(":clock11:", new int[]{0x1f55a});
        temp.put(":round_pushpin:", new int[]{0x1f4cd});
        temp.put(":beers:", new int[]{0x1f37b});
        temp.put(":no_smoking:", new int[]{0x1f6ad});
        temp.put(":menorah:", new int[]{0x1f54e});
        temp.put(":muscle:", new int[]{0x1f4aa});
        temp.put(":game_die:", new int[]{0x1f3b2});
        temp.put(":negative_squared_cross_mark:", new int[]{0x274e});
        temp.put(":mortar_board:", new int[]{0x1f393});
        temp.put(":flag-th:", new int[]{0x1f1f9, 0x1f1ed});
        temp.put(":restroom:", new int[]{0x1f6bb});
        temp.put(":v:", new int[]{0x270c});
        temp.put(":couple_with_heart:", new int[]{0x1f491});
        temp.put(":dragon:", new int[]{0x1f409});
        temp.put(":bookmark:", new int[]{0x1f516});
        temp.put(":envelope_with_arrow:", new int[]{0x1f4e9});
        temp.put(":hotdog:", new int[]{0x1f32d});
        temp.put(":musical_keyboard:", new int[]{0x1f3b9});
        temp.put(":flag-vg:", new int[]{0x1f1fb, 0x1f1ec});
        temp.put(":rice_ball:", new int[]{0x1f359});
        temp.put(":flag-cw:", new int[]{0x1f1e8, 0x1f1fc});
        temp.put(":shower:", new int[]{0x1f6bf});
        temp.put(":asterisk:", new int[]{0x002a, 0x20e3});
        temp.put(":flag-lk:", new int[]{0x1f1f1, 0x1f1f0});
        temp.put(":twisted_rightwards_arrows:", new int[]{0x1f500});
        temp.put(":man_in_suit:", new int[]{0x1f574});
        temp.put(":flag-kw:", new int[]{0x1f1f0, 0x1f1fc});
        temp.put(":blue_book:", new int[]{0x1f4d8});
        temp.put(":ski:", new int[]{0x1f3bf});
        temp.put(":flag-az:", new int[]{0x1f1e6, 0x1f1ff});
        temp.put(":boot:", new int[]{0x1f462});
        temp.put(":atm:", new int[]{0x1f3e7});
        temp.put(":rocket:", new int[]{0x1f680});
        temp.put(":seat:", new int[]{0x1f4ba});
        temp.put(":clock4:", new int[]{0x1f553});
        temp.put(":meat_on_bone:", new int[]{0x1f356});
        temp.put(":scorpion:", new int[]{0x1f982});
        temp.put(":flag-tw:", new int[]{0x1f1f9, 0x1f1fc});
        temp.put(":fist:", new int[]{0x270a});
        temp.put(":flag-gy:", new int[]{0x1f1ec, 0x1f1fe});
        temp.put(":man_with_turban:", new int[]{0x1f473});
        temp.put(":rabbit2:", new int[]{0x1f407});
        temp.put(":flag-tt:", new int[]{0x1f1f9, 0x1f1f9});
        temp.put(":m:", new int[]{0x24c2});
        temp.put(":cloud:", new int[]{0x2601});
        temp.put(":flag-to:", new int[]{0x1f1f9, 0x1f1f4});
        temp.put(":flag-ua:", new int[]{0x1f1fa, 0x1f1e6});
        temp.put(":flag-bh:", new int[]{0x1f1e7, 0x1f1ed});
        temp.put(":customs:", new int[]{0x1f6c3});
        temp.put(":flag-bl:", new int[]{0x1f1e7, 0x1f1f1});
        temp.put(":koko:", new int[]{0x1f201});
        temp.put(":flag-io:", new int[]{0x1f1ee, 0x1f1f4});
        temp.put(":coffee:", new int[]{0x2615});
        temp.put(":laughing:", new int[]{0x1f606});
        temp.put(":flag-vc:", new int[]{0x1f1fb, 0x1f1e8});
        temp.put(":flag_ws:", new int[]{0x1f1fc, 0x1f1f8});
        temp.put(":flag-bb:", new int[]{0x1f1e7, 0x1f1e7});
        temp.put(":keyboard:", new int[]{0x2328});
        temp.put(":bus:", new int[]{0x1f68c});
        temp.put(":scream_cat:", new int[]{0x1f640});
        temp.put(":tv:", new int[]{0x1f4fa});
        temp.put(":peace:", new int[]{0x262e});
        temp.put(":e-mail:", new int[]{0x1f4e7});
        temp.put(":mute:", new int[]{0x1f507});
        temp.put(":imp:", new int[]{0x1f47f});
        temp.put(":six_pointed_star:", new int[]{0x1f52f});
        temp.put(":flag-bd:", new int[]{0x1f1e7, 0x1f1e9});
        temp.put(":tm:", new int[]{0x2122});
        temp.put(":flag-ee:", new int[]{0x1f1ea, 0x1f1ea});
        temp.put(":copyright:", new int[]{0x00a9});
        temp.put(":loop:", new int[]{0x27bf});
        temp.put(":stars:", new int[]{0x1f320});
        temp.put(":flag-ke:", new int[]{0x1f1f0, 0x1f1ea});
        temp.put(":chains:", new int[]{0x26d3});
        temp.put(":arrow_heading_up:", new int[]{0x2934});
        temp.put(":virgo:", new int[]{0x264d});
        temp.put(":star2:", new int[]{0x1f31f});
        temp.put(":fountain:", new int[]{0x26f2});
        temp.put(":fallen_leaf:", new int[]{0x1f342});
        temp.put(":ear:", new int[]{0x1f442});
        temp.put(":eight_pointed_black_star:", new int[]{0x2734});
        temp.put(":pound:", new int[]{0x1f4b7});
        temp.put(":innocent:", new int[]{0x1f607});
        temp.put(":flags:", new int[]{0x1f38f});
        temp.put(":guardsman:", new int[]{0x1f482});
        temp.put(":flag-np:", new int[]{0x1f1f3, 0x1f1f5});
        temp.put(":dragon_face:", new int[]{0x1f432});
        temp.put(":flag-nz:", new int[]{0x1f1f3, 0x1f1ff});
        temp.put(":smoking:", new int[]{0x1f6ac});
        temp.put(":mount_fuji:", new int[]{0x1f5fb});
        temp.put(":lipstick:", new int[]{0x1f484});
        temp.put(":frog:", new int[]{0x1f438});
        temp.put(":registered:", new int[]{0x00ae});
        temp.put(":mask:", new int[]{0x1f637});
        temp.put(":raising_hand:", new int[]{0x1f64b});
        temp.put(":flag-lv:", new int[]{0x1f1f1, 0x1f1fb});
        temp.put(":flag-mg:", new int[]{0x1f1f2, 0x1f1ec});
        temp.put(":sweat_smile:", new int[]{0x1f605});
        temp.put(":children_crossing:", new int[]{0x1f6b8});
        temp.put(":book:", new int[]{0x1f4d6});
        temp.put(":vhs:", new int[]{0x1f4fc});
        temp.put(":alembic:", new int[]{0x2697});
        temp.put(":two:", new int[]{0x0032, 0x20e3});
        temp.put(":tulip:", new int[]{0x1f337});
        temp.put(":beetle:", new int[]{0x1f41e});
        temp.put(":flag-mc:", new int[]{0x1f1f2, 0x1f1e8});
        temp.put(":aries:", new int[]{0x2648});
        temp.put(":flag-ru:", new int[]{0x1f1f7, 0x1f1fa});
        temp.put(":couple:", new int[]{0x1f46b});
        temp.put(":congratulations:", new int[]{0x3297});
        temp.put(":factory:", new int[]{0x1f3ed});
        temp.put(":speak_no_evil:", new int[]{0x1f64a});
        temp.put(":turtle:", new int[]{0x1f422});
        temp.put(":u6709:", new int[]{0x1f236});
        temp.put(":hole:", new int[]{0x1f573});
        temp.put(":mouse:", new int[]{0x1f42d});
        temp.put(":clock2:", new int[]{0x1f551});
        temp.put(":racehorse:", new int[]{0x1f40e});
        temp.put(":man_with_gua_pi_mao:", new int[]{0x1f472});
        temp.put(":bread:", new int[]{0x1f35e});
        temp.put(":heartpulse:", new int[]{0x1f497});
        temp.put(":clock530:", new int[]{0x1f560});
        temp.put(":ballot_box_with_check:", new int[]{0x2611});
        temp.put(":love_letter:", new int[]{0x1f48c});
        temp.put(":snowboarder:", new int[]{0x1f3c2});
        temp.put(":zipper_mouth:", new int[]{0x1f910});
        temp.put(":roller_coaster:", new int[]{0x1f3a2});
        temp.put(":birthday:", new int[]{0x1f382});
        temp.put(":gem:", new int[]{0x1f48e});
        temp.put(":clock330:", new int[]{0x1f55e});
        temp.put(":flag-ky:", new int[]{0x1f1f0, 0x1f1fe});
        temp.put(":watch:", new int[]{0x231a});
        temp.put(":fleur-de-lis:", new int[]{0x269c});
        temp.put(":passport_control:", new int[]{0x1f6c2});
        temp.put(":convenience_store:", new int[]{0x1f3ea});
        temp.put(":accept:", new int[]{0x1f251});
        temp.put(":parking:", new int[]{0x1f17f});
        temp.put(":blush:", new int[]{0x1f60a});
        temp.put(":ferris_wheel:", new int[]{0x1f3a1});
        temp.put(":fork_and_knife:", new int[]{0x1f374});
        temp.put(":u7121:", new int[]{0x1f21a});
        temp.put(":flag-es:", new int[]{0x1f1ea, 0x1f1f8});
        temp.put(":ab:", new int[]{0x1f18e});
        temp.put(":wc:", new int[]{0x1f6be});
        temp.put(":trumpet:", new int[]{0x1f3ba});
        temp.put(":hugging:", new int[]{0x1f917});
        temp.put(":zzz:", new int[]{0x1f4a4});
        temp.put(":zero:", new int[]{0x0030, 0x20e3});
        temp.put(":flag_zm:", new int[]{0x1f1ff, 0x1f1f2});
        temp.put(":flag-je:", new int[]{0x1f1ef, 0x1f1ea});
        temp.put(":flag-sn:", new int[]{0x1f1f8, 0x1f1f3});
        temp.put(":printer:", new int[]{0x1f5a8});
        temp.put(":unamused:", new int[]{0x1f612});
        temp.put(":kimono:", new int[]{0x1f458});
        temp.put(":reminder_ribbon:", new int[]{0x1f397});
        temp.put(":airplane_arriving:", new int[]{0x1f6ec});
        temp.put(":mushroom:", new int[]{0x1f344});
        temp.put(":sparkles:", new int[]{0x2728});
        temp.put(":necktie:", new int[]{0x1f454});
        temp.put(":leopard:", new int[]{0x1f406});
        temp.put(":fries:", new int[]{0x1f35f});
        temp.put(":flag-mm:", new int[]{0x1f1f2, 0x1f1f2});
        temp.put(":clock10:", new int[]{0x1f559});
        temp.put(":snowman:", new int[]{0x26c4});
        temp.put(":green_book:", new int[]{0x1f4d7});
        temp.put(":bow_and_arrow:", new int[]{0x1f3f9});
        temp.put(":flag-bz:", new int[]{0x1f1e7, 0x1f1ff});
        temp.put(":blue_car:", new int[]{0x1f699});
        temp.put(":flag-bq:", new int[]{0x1f1e7, 0x1f1f6});
        temp.put(":pineapple:", new int[]{0x1f34d});

        temp.forEach((key, ints) -> {
            StringBuilder current = new StringBuilder();
            for(int i : ints){
                current.append(Character.toChars(i));
            }
            SHORTCODE_MAP.put(key, current.toString());
        });
    }

    public static Optional<String> getEmojiFromShortcode(String shortCode){
        return Optional.ofNullable(
                SHORTCODE_MAP.get(shortCode)
        );
    }

    public static Map<String, String> getShortcodeMap(){
        return Collections.unmodifiableMap(SHORTCODE_MAP);
    }

    public static Optional<URI> getEmojiURI(Integer emojiId){
        return Optional.ofNullable(emojiId)
                .map("?id=%d"::formatted)
                .map(EMOJI_BASE_PATH::resolve);
    }
}
